### ISSUE TITLE
Migrate to v1.2

### ISSUE THREAD

**Issue by andrejrakic** [smartcontractkit/ccip-starter-kit-foundry#11]
Testnet addresses currently present in the `Helper.sol` file are deprecated now. We need to upgrade them to v1.2 addresses and add support for Wemix and Kroma Sepolia testnets.

**Comment by kamuik16** [comment]
> Testnet addresses currently present in the `Helper.sol` file are deprecated now. We need to upgrade them to v1.2 addresses and add support for Wemix and Kroma Sepolia testnets.

Would love to take this up!

**Comment by kamuik16** [comment]
> > Would love to take this up!
> 
> That would be amazing @kamuik16, thank you!
> 
> Feel free to check https://docs.chain.link/ccip/supported-networks/v1_2_0/testnet for details and remove deprecated test networks like Base Goerli. Once PR is ready please tag me for a review so I don't miss it 😄
> 
> Thanks once again

Looking at the Router, Link and WETH address and verifying it with the [docs](https://docs.chain.link/ccip/supported-networks/v1_2_0/testnet#overview) it seems fine. I see that Base Goerli is deprecated and new Wemix and Kroma Sepolia testnets are added. Am I missing something?

**Comment by kamuik16** [comment]
> > > > Would love to take this up!
> > > 
> > > 
> > > That would be amazing @kamuik16, thank you!
> > > Feel free to check https://docs.chain.link/ccip/supported-networks/v1_2_0/testnet for details and remove deprecated test networks like Base Goerli. Once PR is ready please tag me for a review so I don't miss it 😄
> > > Thanks once again
> > 
> > 
> > Looking at the Router, Link and WETH address and verifying it with the [docs](https://docs.chain.link/ccip/supported-networks/v1_2_0/testnet#overview) it seems fine. I see that Base Goerli is deprecated and new Wemix and Kroma Sepolia testnets are added. Am I missing something?
> 
> Nope, that's it!

So, to sum it up, so I don't get it wrong :|. I need to remove Base Goerli and add Wemix and Kroma Sepolia and not touch anything else. Correct me if I am wrong :)
